version: "3.8"

services:
  api:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgree:5432/todolist
    depends_on:
      - postgree

  postgree:
    image: postgres:latest
    container_name: postgreeServer
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todolist
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
