services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysqlpsw
      MYSQL_DATABASE: db_project
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
